// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	messages "github.com/dragranzer/capstone-BE-FGD/features/messages"
	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// DeleteMessagesbyId provides a mock function with given fields: data
func (_m *Data) DeleteMessagesbyId(data messages.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(messages.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertMessages provides a mock function with given fields: data
func (_m *Data) InsertMessages(data messages.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(messages.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectMessagesbyAdminID provides a mock function with given fields: data
func (_m *Data) SelectMessagesbyAdminID(data messages.Core) ([]messages.Core, error) {
	ret := _m.Called(data)

	var r0 []messages.Core
	if rf, ok := ret.Get(0).(func(messages.Core) []messages.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]messages.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(messages.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
