// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	favorites "github.com/dragranzer/capstone-BE-FGD/features/favorites"
	mock "github.com/stretchr/testify/mock"
)

// Bussiness is an autogenerated mock type for the Bussiness type
type Bussiness struct {
	mock.Mock
}

// DeleteFavorite provides a mock function with given fields: data
func (_m *Bussiness) DeleteFavorite(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteThreadbyId provides a mock function with given fields: data
func (_m *Bussiness) DeleteThreadbyId(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllFavorite provides a mock function with given fields: data
func (_m *Bussiness) GetAllFavorite(data favorites.Core) ([]favorites.Core, error) {
	ret := _m.Called(data)

	var r0 []favorites.Core
	if rf, ok := ret.Get(0).(func(favorites.Core) []favorites.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]favorites.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(favorites.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertFavorite provides a mock function with given fields: data
func (_m *Bussiness) InsertFavorite(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
