// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	favorites "github.com/dragranzer/capstone-BE-FGD/features/favorites"
	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// AddFavorite provides a mock function with given fields: data
func (_m *Data) AddFavorite(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFavorite provides a mock function with given fields: data
func (_m *Data) DeleteFavorite(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFavoritebyThreadId provides a mock function with given fields: data
func (_m *Data) DeleteFavoritebyThreadId(data favorites.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(favorites.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectAllFavorite provides a mock function with given fields: data
func (_m *Data) SelectAllFavorite(data favorites.Core) ([]favorites.Core, error) {
	ret := _m.Called(data)

	var r0 []favorites.Core
	if rf, ok := ret.Get(0).(func(favorites.Core) []favorites.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]favorites.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(favorites.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
