// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	categories "github.com/dragranzer/capstone-BE-FGD/features/categories"
	mock "github.com/stretchr/testify/mock"
)

// Data is an autogenerated mock type for the Data type
type Data struct {
	mock.Mock
}

// DeleteCategorybyId provides a mock function with given fields: data
func (_m *Data) DeleteCategorybyId(data categories.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(categories.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertCategory provides a mock function with given fields: data
func (_m *Data) InsertCategory(data categories.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(categories.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectAllCategory provides a mock function with given fields: data
func (_m *Data) SelectAllCategory(data categories.Core) ([]categories.Core, error) {
	ret := _m.Called(data)

	var r0 []categories.Core
	if rf, ok := ret.Get(0).(func(categories.Core) []categories.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]categories.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(categories.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectCategorybyId provides a mock function with given fields: data
func (_m *Data) SelectCategorybyId(data categories.Core) (categories.Core, error) {
	ret := _m.Called(data)

	var r0 categories.Core
	if rf, ok := ret.Get(0).(func(categories.Core) categories.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(categories.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(categories.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectCategorybyName provides a mock function with given fields: data
func (_m *Data) SelectCategorybyName(data categories.Core) (categories.Core, error) {
	ret := _m.Called(data)

	var r0 categories.Core
	if rf, ok := ret.Get(0).(func(categories.Core) categories.Core); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(categories.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(categories.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: data
func (_m *Data) UpdateCategory(data categories.Core) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(categories.Core) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
